version: '3.5'

services:
  k-db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-pass
    networks:
      - k-network
  k-redis:
    image: redis:5-alpine
    networks:
      - k-network
  example-backend:
    image: example-backend
    build: ./example-backend-service
    restart: on-failure
    networks:
      - k-network
    depends_on:
      - k-db
      - k-redis
    environment:
      - spring.datasource.url=jdbc:mysql://k-db:3306/
      - spring.datasource.username=root
      - spring.datasource.password=my-pass
networks:
  k-network:
