spring:
  jpa:
    hibernate:
      use-new-id-generator-mappings: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        id.new_generator_mappings: false
        format_sql: true
    show-sql: true
  session:
    store-type: redis
    timeout: 300
    redis:
      flush-mode: immediate
      namespace: spring:session
